Repository elastic/elastic-transport-net, pull requests merged in 2020-11, with the labels that each got.

#2 Add initial benchmark project to the solution
  benchmarks/Elastic.Transport.Benchmarks/Elastic.Transport.Benchmarks.csproj
  benchmarks/Elastic.Transport.Benchmarks/Program.cs
  benchmarks/Elastic.Transport.Benchmarks/TransportBenchmarks.cs
  elastic-transport-net.sln
Labels: enhancement, v0.2.0

#8 add junit logger
  tests/Elastic.Transport.Tests/Elastic.Transport.Tests.csproj
Labels: Infra, bug, v0.2.0

#7 Enable .NET 5 SDK
  .github/workflows/ci.yml
  Directory.Build.props
  benchmarks/Elastic.Transport.Benchmarks/Elastic.Transport.Benchmarks.csproj
  benchmarks/Elastic.Transport.Benchmarks/Program.cs
  build/scripts/scripts.fsproj
  dotnet-tools.json
  global.json
  tests/Elastic.Transport.Tests/Elastic.Transport.Tests.csproj
Labels: Infra, v0.2.0

#9 Add fix for ServerError after moving to .NET5
  .github/workflows/ci.yml
  build/scripts/scripts.fsproj
  src/Elastic.Transport/Components/Connection/HttpWebRequestConnection.cs
  src/Elastic.Transport/Configuration/UserAgent.cs
  src/Elastic.Transport/Diagnostics/Diagnostic.cs
  src/Elastic.Transport/Elastic.Transport.csproj
  src/Elastic.Transport/Products/Elasticsearch/Failures/ServerError.cs
Labels: bug, v0.2.0

#10 Several refactorings for transport
  src/Elastic.Transport.VirtualizedCluster/Components/ExposingPipelineFactory.cs
  src/Elastic.Transport.VirtualizedCluster/Components/VirtualizedCluster.cs
  src/Elastic.Transport/Components/Connection/HttpConnection.cs
  src/Elastic.Transport/Components/Connection/IConnection.cs
  src/Elastic.Transport/Components/ConnectionPool/CloudConnectionPool.cs
  src/Elastic.Transport/Components/ConnectionPool/Node.cs
  src/Elastic.Transport/Components/Pipeline/IRequestPipeline.cs
  src/Elastic.Transport/Components/Pipeline/PipelineFailure.cs
  src/Elastic.Transport/Components/Pipeline/RequestData.cs
  src/Elastic.Transport/Components/Pipeline/RequestPipeline.cs
  src/Elastic.Transport/Components/Pipeline/ResponseBuilder.cs
  src/Elastic.Transport/Components/Providers/IDateTimeProvider.cs
  src/Elastic.Transport/Components/Providers/IRequestPipelineFactory.cs
  src/Elastic.Transport/Components/Serialization/ISerializer.cs
  src/Elastic.Transport/Configuration/ITransportConfiguration.cs
  src/Elastic.Transport/Configuration/RequestConfiguration.cs
  src/Elastic.Transport/Configuration/TransportConfiguration.cs
  src/Elastic.Transport/Diagnostics/Auditing/AuditEvent.cs
  src/Elastic.Transport/Exceptions/TransportException.cs
  src/Elastic.Transport/ITransport.cs
  src/Elastic.Transport/Products/DefaultProductRegistration.cs
  src/Elastic.Transport/Products/Elasticsearch/ElasticsearchProductRegistration.cs
  src/Elastic.Transport/Products/Elasticsearch/ElasticsearchResponse.cs
  src/Elastic.Transport/Products/IProductRegistration.cs
  src/Elastic.Transport/Requests/Body/PostData.ByteArray.cs
  src/Elastic.Transport/Requests/Body/PostData.MultiJson.cs
  src/Elastic.Transport/Requests/Body/PostData.ReadOnlyMemory.cs
  src/Elastic.Transport/Requests/Body/PostData.Serializable.cs
  src/Elastic.Transport/Requests/Body/PostData.Streamable.cs
  src/Elastic.Transport/Requests/Body/PostData.String.cs
  src/Elastic.Transport/Requests/Body/PostData.cs
  src/Elastic.Transport/Requests/IRequestParameters.cs
  src/Elastic.Transport/Requests/IUrlParameter.cs
  src/Elastic.Transport/Requests/RequestParameters.cs
  src/Elastic.Transport/Requests/UrlFormatter.cs
  src/Elastic.Transport/Responses/HttpDetails/ApiCallDetails.cs
  src/Elastic.Transport/Responses/HttpDetails/IApiCallDetails.cs
  src/Elastic.Transport/Responses/TransportResponseBase.cs
  src/Elastic.Transport/Transport.cs
  tests/Elastic.Transport.Tests/ResponseBuilderDisposeTests.cs
  tests/Elastic.Transport.Tests/Test.cs
Labels: enhancement, v0.2.1

#12 Add .NET 5.0 TFM and sync HttpClient
  src/Elastic.Transport/Components/Connection/HttpConnection.cs
  src/Elastic.Transport/Elastic.Transport.csproj
Labels: Infra, v0.2.1
