Repository elastic/elastic-transport-net, pull requests merged in 2024-11, with the labels that each got.

#133 Add copy constructor to `RequestConfiguration{Descriptor}`
  src/Elastic.Transport/Components/Pipeline/RequestPipeline.cs
  src/Elastic.Transport/Configuration/RequestConfiguration.cs
  tests/Elastic.Transport.Tests/Configuration/RequestConfigurationTests.cs
Labels: v0.5.2

#134 Add support for response builders on IRequestConfiguration
  global.json
  src/Elastic.Transport/Components/Pipeline/RequestData.cs
  src/Elastic.Transport/Components/TransportClient/HttpRequestInvoker.cs
  src/Elastic.Transport/Components/TransportClient/HttpWebRequestInvoker.cs
  src/Elastic.Transport/Configuration/IRequestConfiguration.cs
  src/Elastic.Transport/Configuration/ITransportConfiguration.cs
  src/Elastic.Transport/Configuration/RequestConfiguration.cs
  src/Elastic.Transport/Configuration/RequestConfigurationDescriptor.cs
  src/Elastic.Transport/Configuration/TransportConfigurationDescriptor.cs
  src/Elastic.Transport/Responses/DefaultResponseFactory.cs
  tests/Elastic.Transport.Tests/Configuration/RequestConfigurationTests.cs
Labels: v0.5.2

#136 Add `RequestConfigurationDescriptor` copy constructor
  src/Elastic.Transport/Configuration/RequestConfiguration.cs
  src/Elastic.Transport/Configuration/RequestConfigurationDescriptor.cs
  src/Elastic.Transport/Configuration/TransportConfiguration.cs
  src/Elastic.Transport/Configuration/TransportConfigurationDescriptor.cs
  src/Elastic.Transport/Elastic.Transport.csproj
  tests/Elastic.Transport.Tests/Configuration/TransportConfigurationTests.cs
Labels: enhancement, v0.5.3

#135 Improve `UrlFormatter`
  src/Elastic.Transport/Requests/UrlFormatter.cs
Labels: enhancement, v0.5.3

#141 Replace `RequestData` with `BoundConfiguration`
  src/Elastic.Transport.VirtualizedCluster/Components/ExposingPipelineFactory.cs
  src/Elastic.Transport.VirtualizedCluster/Components/VirtualClusterConnection.cs
  src/Elastic.Transport.VirtualizedCluster/Rules/RuleBase.cs
  src/Elastic.Transport/Components/Pipeline/BoundConfiguration.cs
  src/Elastic.Transport/Components/Pipeline/DefaultResponseBuilder.cs
  src/Elastic.Transport/Components/Pipeline/RequestPipeline.cs
  src/Elastic.Transport/Components/Providers/DefaultRequestPipelineFactory.cs
  src/Elastic.Transport/Components/Providers/RequestPipelineFactory.cs
  src/Elastic.Transport/Components/TransportClient/Content/RequestDataContent.cs
  src/Elastic.Transport/Components/TransportClient/HandlerTracking/RequestDataHttpClientFactory.cs
  src/Elastic.Transport/Components/TransportClient/HttpRequestInvoker.cs
  src/Elastic.Transport/Components/TransportClient/HttpWebRequestInvoker.cs
  src/Elastic.Transport/Components/TransportClient/IRequestInvoker.cs
  src/Elastic.Transport/Components/TransportClient/InMemoryRequestInvoker.cs
  src/Elastic.Transport/Configuration/IRequestConfiguration.cs
  src/Elastic.Transport/Configuration/ITransportConfiguration.cs
  src/Elastic.Transport/Configuration/TransportConfiguration.cs
  src/Elastic.Transport/Configuration/TransportConfigurationDescriptor.cs
  src/Elastic.Transport/Diagnostics/HttpConnectionDiagnosticObserver.cs
  src/Elastic.Transport/Diagnostics/RequestPipelineDiagnosticObserver.cs
  src/Elastic.Transport/DistributedTransport.cs
  src/Elastic.Transport/ITransport.cs
  src/Elastic.Transport/Products/DefaultProductRegistration.cs
  src/Elastic.Transport/Products/Elasticsearch/ElasticsearchErrorExtensions.cs
  src/Elastic.Transport/Products/Elasticsearch/ElasticsearchProductRegistration.cs
  src/Elastic.Transport/Products/Elasticsearch/ElasticsearchResponseBuilder.cs
  src/Elastic.Transport/Products/ProductRegistration.cs
  src/Elastic.Transport/Requests/MetaData/DefaultMetaHeaderProvider.cs
  src/Elastic.Transport/Requests/MetaData/MetaHeaderProvider.cs
  src/Elastic.Transport/Requests/MetaData/RequestMetaData.cs
  src/Elastic.Transport/Responses/DefaultResponseFactory.cs
  src/Elastic.Transport/Responses/Dynamic/DynamicResponseBuilder.cs
  src/Elastic.Transport/Responses/IResponseBuilder.cs
  src/Elastic.Transport/Responses/ResponseFactory.cs
  src/Elastic.Transport/Responses/Special/BytesResponseBuilder.cs
  src/Elastic.Transport/Responses/Special/StreamResponseBuilder.cs
  src/Elastic.Transport/Responses/Special/StringResponseBuilder.cs
  src/Elastic.Transport/Responses/Special/VoidResponseBuilder.cs
  src/Elastic.Transport/Responses/TypedResponseBuilder.cs
  tests/Elastic.Transport.IntegrationTests/Plumbing/Stubs/TrackingRequestInvoker.cs
  tests/Elastic.Transport.IntegrationTests/Responses/SpecialisedResponseTests.cs
  tests/Elastic.Transport.Tests/ResponseFactoryDisposeTests.cs
  tests/Elastic.Transport.Tests/Responses/Dynamic/DynamicResponseBuilderTests.cs
  tests/Elastic.Transport.Tests/Responses/Special/BytesResponseBuilderTests.cs
  tests/Elastic.Transport.Tests/Responses/Special/StreamResponseBuilderTests.cs
  tests/Elastic.Transport.Tests/Responses/Special/StringResponseBuilderTests.cs
  tests/Elastic.Transport.Tests/Responses/Special/VoidResponseBuilderTests.cs
Labels: v0.5.4

#144 Null check bug fixes and tweak accessibility of properties on `TransportResponse`
  src/Elastic.Transport/Diagnostics/OpenTelemetry/OpenTelemetry.cs
  src/Elastic.Transport/DistributedTransport.cs
  src/Elastic.Transport/Responses/DefaultResponseFactory.cs
  src/Elastic.Transport/Responses/Special/StreamResponse.cs
  src/Elastic.Transport/Responses/Special/StreamResponseBase.cs
  src/Elastic.Transport/Responses/TransportResponse.cs
Labels: bug, v0.5.5
