Repository elastic/elastic-transport-net, pull requests merged in 2024-10, with the labels that each got.

#118 Update test dependencies and suppress warnings
  Directory.Build.props
  src/Directory.Build.props
  src/Elastic.Transport/Elastic.Transport.csproj
  tests/Elastic.Elasticsearch.IntegrationTests/Elastic.Elasticsearch.IntegrationTests.csproj
  tests/Elastic.Transport.IntegrationTests/Elastic.Transport.IntegrationTests.csproj
  tests/Elastic.Transport.Tests/Elastic.Transport.Tests.csproj
Labels: enhancement, v0.4.23

#119 Add `SystemTextJsonSerializer` base class and relevant extensions methods
  src/Elastic.Transport/Components/Serialization/IJsonSerializerOptionsProvider.cs
  src/Elastic.Transport/Components/Serialization/LowLevelRequestResponseSerializer.cs
  src/Elastic.Transport/Components/Serialization/Serializer.cs
  src/Elastic.Transport/Components/Serialization/SystemTextJsonSerializer.cs
  src/Elastic.Transport/Components/Serialization/TransportSerializerExtensions.cs
Labels: enhancement, v0.4.23

#123 Fix nullability annotations in `SystemTextJsonSerializer`
  src/Elastic.Transport/Components/Serialization/SystemTextJsonSerializer.cs
  src/Elastic.Transport/Components/Serialization/TransportSerializerExtensions.cs
Labels: enhancement, v0.4.24

#124 Add `TryGetJsonSerializerOptions` extension method
  src/Elastic.Transport/Components/Serialization/TransportSerializerExtensions.cs
Labels: enhancement, v0.4.25

#125 Remove `MemoryStreamFactory` default value from `Serialize` extensions
  src/Elastic.Transport/Components/Serialization/TransportSerializerExtensions.cs
Labels: enhancement, v0.4.26
